"""initial migration

Revision ID: 20260526_215644
Revises:
Create Date: 2026-05-26 21:56:44.923635

"""

# Standard library
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "20260526_215644"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
