default_language_version:
  python: python3.14

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format project_name tests packages/example_lib
        language: system
        pass_filenames: false

      - id: ruff-check
        name: ruff check
        entry: uv run ruff check --fix project_name tests packages/example_lib
        language: system
        pass_filenames: false

      - id: basedpyright
        name: basedpyright
        entry: uv run basedpyright project_name tests packages/example_lib
        language: system
        pass_filenames: false
